//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace espol.sd.app.ServicioDB {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IServicioDB", Namespace="http://tempuri.org/")]
    public partial class ServicioDB : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SaveGifsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ImportGifsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ResetAccesosGifsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SelectTop10GifsDBIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback SelectTop10GifsDBOperationCompleted;
        
        private System.Threading.SendOrPostCallback SelectTop10GifsCacheOperationCompleted;
        
        private System.Threading.SendOrPostCallback SimularAccesoGifsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServicioDB() {
            this.Url = global::espol.sd.app.Properties.Settings.Default.espol_sd_app_ServicioDB_ServicioDB;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SaveGifsCompletedEventHandler SaveGifsCompleted;
        
        /// <remarks/>
        public event ImportGifsCompletedEventHandler ImportGifsCompleted;
        
        /// <remarks/>
        public event ResetAccesosGifsCompletedEventHandler ResetAccesosGifsCompleted;
        
        /// <remarks/>
        public event SelectTop10GifsDBIdCompletedEventHandler SelectTop10GifsDBIdCompleted;
        
        /// <remarks/>
        public event SelectTop10GifsDBCompletedEventHandler SelectTop10GifsDBCompleted;
        
        /// <remarks/>
        public event SelectTop10GifsCacheCompletedEventHandler SelectTop10GifsCacheCompleted;
        
        /// <remarks/>
        public event SimularAccesoGifsCompletedEventHandler SimularAccesoGifsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServicioDB/SaveGifs", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] SaveGifs() {
            object[] results = this.Invoke("SaveGifs", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void SaveGifsAsync() {
            this.SaveGifsAsync(null);
        }
        
        /// <remarks/>
        public void SaveGifsAsync(object userState) {
            if ((this.SaveGifsOperationCompleted == null)) {
                this.SaveGifsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveGifsOperationCompleted);
            }
            this.InvokeAsync("SaveGifs", new object[0], this.SaveGifsOperationCompleted, userState);
        }
        
        private void OnSaveGifsOperationCompleted(object arg) {
            if ((this.SaveGifsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveGifsCompleted(this, new SaveGifsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServicioDB/ImportGifs", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] ImportGifs() {
            object[] results = this.Invoke("ImportGifs", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void ImportGifsAsync() {
            this.ImportGifsAsync(null);
        }
        
        /// <remarks/>
        public void ImportGifsAsync(object userState) {
            if ((this.ImportGifsOperationCompleted == null)) {
                this.ImportGifsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnImportGifsOperationCompleted);
            }
            this.InvokeAsync("ImportGifs", new object[0], this.ImportGifsOperationCompleted, userState);
        }
        
        private void OnImportGifsOperationCompleted(object arg) {
            if ((this.ImportGifsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ImportGifsCompleted(this, new ImportGifsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServicioDB/ResetAccesosGifs", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] ResetAccesosGifs() {
            object[] results = this.Invoke("ResetAccesosGifs", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void ResetAccesosGifsAsync() {
            this.ResetAccesosGifsAsync(null);
        }
        
        /// <remarks/>
        public void ResetAccesosGifsAsync(object userState) {
            if ((this.ResetAccesosGifsOperationCompleted == null)) {
                this.ResetAccesosGifsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnResetAccesosGifsOperationCompleted);
            }
            this.InvokeAsync("ResetAccesosGifs", new object[0], this.ResetAccesosGifsOperationCompleted, userState);
        }
        
        private void OnResetAccesosGifsOperationCompleted(object arg) {
            if ((this.ResetAccesosGifsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ResetAccesosGifsCompleted(this, new ResetAccesosGifsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServicioDB/SelectTop10GifsDBId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RespuestaMetodoTop10Gifs SelectTop10GifsDBId() {
            object[] results = this.Invoke("SelectTop10GifsDBId", new object[0]);
            return ((RespuestaMetodoTop10Gifs)(results[0]));
        }
        
        /// <remarks/>
        public void SelectTop10GifsDBIdAsync() {
            this.SelectTop10GifsDBIdAsync(null);
        }
        
        /// <remarks/>
        public void SelectTop10GifsDBIdAsync(object userState) {
            if ((this.SelectTop10GifsDBIdOperationCompleted == null)) {
                this.SelectTop10GifsDBIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectTop10GifsDBIdOperationCompleted);
            }
            this.InvokeAsync("SelectTop10GifsDBId", new object[0], this.SelectTop10GifsDBIdOperationCompleted, userState);
        }
        
        private void OnSelectTop10GifsDBIdOperationCompleted(object arg) {
            if ((this.SelectTop10GifsDBIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectTop10GifsDBIdCompleted(this, new SelectTop10GifsDBIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServicioDB/SelectTop10GifsDB", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RespuestaMetodoTop10Gifs SelectTop10GifsDB() {
            object[] results = this.Invoke("SelectTop10GifsDB", new object[0]);
            return ((RespuestaMetodoTop10Gifs)(results[0]));
        }
        
        /// <remarks/>
        public void SelectTop10GifsDBAsync() {
            this.SelectTop10GifsDBAsync(null);
        }
        
        /// <remarks/>
        public void SelectTop10GifsDBAsync(object userState) {
            if ((this.SelectTop10GifsDBOperationCompleted == null)) {
                this.SelectTop10GifsDBOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectTop10GifsDBOperationCompleted);
            }
            this.InvokeAsync("SelectTop10GifsDB", new object[0], this.SelectTop10GifsDBOperationCompleted, userState);
        }
        
        private void OnSelectTop10GifsDBOperationCompleted(object arg) {
            if ((this.SelectTop10GifsDBCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectTop10GifsDBCompleted(this, new SelectTop10GifsDBCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServicioDB/SelectTop10GifsCache", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RespuestaMetodoTop10Gifs SelectTop10GifsCache() {
            object[] results = this.Invoke("SelectTop10GifsCache", new object[0]);
            return ((RespuestaMetodoTop10Gifs)(results[0]));
        }
        
        /// <remarks/>
        public void SelectTop10GifsCacheAsync() {
            this.SelectTop10GifsCacheAsync(null);
        }
        
        /// <remarks/>
        public void SelectTop10GifsCacheAsync(object userState) {
            if ((this.SelectTop10GifsCacheOperationCompleted == null)) {
                this.SelectTop10GifsCacheOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectTop10GifsCacheOperationCompleted);
            }
            this.InvokeAsync("SelectTop10GifsCache", new object[0], this.SelectTop10GifsCacheOperationCompleted, userState);
        }
        
        private void OnSelectTop10GifsCacheOperationCompleted(object arg) {
            if ((this.SelectTop10GifsCacheCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectTop10GifsCacheCompleted(this, new SelectTop10GifsCacheCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServicioDB/SimularAccesoGifs", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)]
        public int[] SimularAccesoGifs(int NumeroClientes, [System.Xml.Serialization.XmlIgnoreAttribute()] bool NumeroClientesSpecified) {
            object[] results = this.Invoke("SimularAccesoGifs", new object[] {
                        NumeroClientes,
                        NumeroClientesSpecified});
            return ((int[])(results[0]));
        }
        
        /// <remarks/>
        public void SimularAccesoGifsAsync(int NumeroClientes, bool NumeroClientesSpecified) {
            this.SimularAccesoGifsAsync(NumeroClientes, NumeroClientesSpecified, null);
        }
        
        /// <remarks/>
        public void SimularAccesoGifsAsync(int NumeroClientes, bool NumeroClientesSpecified, object userState) {
            if ((this.SimularAccesoGifsOperationCompleted == null)) {
                this.SimularAccesoGifsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSimularAccesoGifsOperationCompleted);
            }
            this.InvokeAsync("SimularAccesoGifs", new object[] {
                        NumeroClientes,
                        NumeroClientesSpecified}, this.SimularAccesoGifsOperationCompleted, userState);
        }
        
        private void OnSimularAccesoGifsOperationCompleted(object arg) {
            if ((this.SimularAccesoGifsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SimularAccesoGifsCompleted(this, new SimularAccesoGifsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/espol.sd.db")]
    public partial class RespuestaMetodoTop10Gifs {
        
        private string codigoRetornoField;
        
        private GifImage[] imagenesField;
        
        private string mensajeRetornoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CodigoRetorno {
            get {
                return this.codigoRetornoField;
            }
            set {
                this.codigoRetornoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public GifImage[] Imagenes {
            get {
                return this.imagenesField;
            }
            set {
                this.imagenesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MensajeRetorno {
            get {
                return this.mensajeRetornoField;
            }
            set {
                this.mensajeRetornoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2558.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/espol.sd.db")]
    public partial class GifImage {
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private byte[] imagenField;
        
        private string nombreField;
        
        private int numAccesosField;
        
        private bool numAccesosFieldSpecified;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] Imagen {
            get {
                return this.imagenField;
            }
            set {
                this.imagenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
        
        /// <remarks/>
        public int NumAccesos {
            get {
                return this.numAccesosField;
            }
            set {
                this.numAccesosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NumAccesosSpecified {
            get {
                return this.numAccesosFieldSpecified;
            }
            set {
                this.numAccesosFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void SaveGifsCompletedEventHandler(object sender, SaveGifsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveGifsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveGifsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void ImportGifsCompletedEventHandler(object sender, ImportGifsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ImportGifsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ImportGifsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void ResetAccesosGifsCompletedEventHandler(object sender, ResetAccesosGifsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ResetAccesosGifsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ResetAccesosGifsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void SelectTop10GifsDBIdCompletedEventHandler(object sender, SelectTop10GifsDBIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectTop10GifsDBIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelectTop10GifsDBIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RespuestaMetodoTop10Gifs Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RespuestaMetodoTop10Gifs)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void SelectTop10GifsDBCompletedEventHandler(object sender, SelectTop10GifsDBCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectTop10GifsDBCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelectTop10GifsDBCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RespuestaMetodoTop10Gifs Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RespuestaMetodoTop10Gifs)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void SelectTop10GifsCacheCompletedEventHandler(object sender, SelectTop10GifsCacheCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectTop10GifsCacheCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelectTop10GifsCacheCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RespuestaMetodoTop10Gifs Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RespuestaMetodoTop10Gifs)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void SimularAccesoGifsCompletedEventHandler(object sender, SimularAccesoGifsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SimularAccesoGifsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SimularAccesoGifsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591